 <!-- vue3 JS & CSS files -->
 <script type="text/javascript" src="<?= $this->helper->basePath('/js/plugin/vue3/vue.global.min.js'); ?>"></script>

 <div id="app">  
    <p>Count: {{ count }}</p>
    <button @click="increment">Increment</button> 
 </div>

 <script type="module"> 
     const {
         createApp,
         ref
     } = Vue
     const app = createApp({
         setup() {
            const count = ref(0);
                const increment = () => {
                count.value++;
                }; 
                return {
                    count,
                    increment
                };
         }
     }) 
     app.mount('#app')
 </script>

 <style scoped> 
 </style>